# Generated by Django 6.0.4 on 2026-04-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resume_pdf',
            field=models.FileField(blank=True, help_text='Upload your resume as a PDF file for public download.', null=True, upload_to='resume/'),
        ),
    ]
