# Generated by Django 6.0.4 on 2026-04-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_sitevisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='calendar_event_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
