# Generated by Django 6.0.4 on 2026-04-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_appointment_calendar_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video',
            field=models.FileField(blank=True, help_text='Upload a demo video (MP4 recommended)', null=True, upload_to='projects/videos/'),
        ),
    ]
