# Generated by Django 6.0.4 on 2026-05-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_project_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='challenge',
            field=models.TextField(blank=True, verbose_name='Biggest Challenge'),
        ),
        migrations.AddField(
            model_name='project',
            name='key_features',
            field=models.TextField(blank=True, help_text='One feature per line', verbose_name='Key Features'),
        ),
        migrations.AddField(
            model_name='project',
            name='learnings',
            field=models.TextField(blank=True, verbose_name='What You Learned'),
        ),
        migrations.AddField(
            model_name='project',
            name='role',
            field=models.TextField(blank=True, verbose_name='Your Role / Contribution'),
        ),
        migrations.AlterField(
            model_name='project',
            name='problem',
            field=models.TextField(blank=True, verbose_name='Business Problem'),
        ),
    ]
