# Generated by Django 6.0.4 on 2026-05-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_project_challenge_project_key_features_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertiseCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='💡', help_text='Paste an emoji e.g. 💡 🖥️ 📊 🤖 🔧', max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('link_text', models.CharField(default='Learn More →', max_length=60)),
                ('link_url', models.CharField(default='/projects/', help_text='Relative URL e.g. /projects/ or /skills/', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Expertise Card',
                'verbose_name_plural': 'Expertise Cards',
                'ordering': ['order'],
            },
        ),
    ]
