# Generated by Django 6.0.4 on 2026-05-09 17:27

import MainApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_projectimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='resume_pdf',
            field=models.FileField(blank=True, help_text='Upload your resume as a PDF file for public download.', null=True, storage=MainApp.models._resume_storage, upload_to='resume/'),
        ),
    ]
